// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ActionTableData } from "./../systems/ActionSystem.sol";

interface IActionSystem {
  function submitAction(uint16 gameID, ActionTableData memory action) external;
}
