// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Direction } from "./../systems/ActionSystem.sol";

interface IActionSystem {
  function punch(address bot, uint16 gameID, uint16 round, address target) external;

  function shoot(address bot, uint16 gameID, uint16 round, address target) external;

  function blast(address bot, uint16 gameID, uint16 round, address target) external;

  function charge(address bot, uint16 gameID, uint16 round) external;

  function move(address bot, uint16 gameID, uint16 round, Direction direction) external;

  function dash(address bot, uint16 gameID, uint16 round, Direction direction) external;
}
