// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAttackSystem {
  function punch(bytes32 targetID) external;

  function shoot(bytes32 targetID) external;

  function blast(bytes32 targetID) external;

  function charge() external;
}
