// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IGameSystem {
  function tmpDeployBots(uint16 gameID) external;

  function createGame() external returns (uint16 gameID);

  function addBot(uint16 gameID, address bot) external;

  function startGame(uint16 gameID) external;

  function nextRound(uint16 gameID) external;
}
