// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Direction } from "./../systems/MoveSystem.sol";

interface IMoveSystem {
  function move(Direction direction) external;

  function dash(Direction direction) external;
}
