// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Direction } from "./../systems/MoveSystem.sol";

interface IMoveSystem {
  function move(bytes32 ID, uint16 gameID, uint16 round, Direction direction) external;

  function dash(bytes32 ID, uint16 gameID, uint16 round, Direction direction) external;
}
