// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ActionTableData } from "./../systems/SubmitSystem.sol";

interface ISubmitSystem {
  function submitAction(uint16 gameID, uint16 index, ActionTableData memory action) external;
}
