/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    GlobalTable: (() => {
      const tableId = new TableId("", "GlobalTable");
      return defineComponent(
        world,
        {
          nextGameID: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    GameTable: (() => {
      const tableId = new TableId("", "GameTable");
      return defineComponent(
        world,
        {
          creator: RecsType.String,
          round: RecsType.Number,
          numBots: RecsType.Number,
          alive: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    BotTable: (() => {
      const tableId = new TableId("", "bot");
      return defineComponent(
        world,
        {
          bot: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    PositionTable: (() => {
      const tableId = new TableId("", "position");
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    ReversePositionTable: (() => {
      const tableId = new TableId("", "reversePosition");
      return defineComponent(
        world,
        {
          bot: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    AttributeTable: (() => {
      const tableId = new TableId("", "attribute");
      return defineComponent(
        world,
        {
          health: RecsType.Number,
          ammo: RecsType.Number,
          rockets: RecsType.Number,
          lastDash: RecsType.Number,
          charge: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    ActionTable: (() => {
      const tableId = new TableId("", "action");
      return defineComponent(
        world,
        {
          actionType: RecsType.Number,
          direction: RecsType.Number,
          target: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
