/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Round: (() => {
      const tableId = new TableId("", "round");
      return defineComponent(
        world,
        {
          round: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    PositionTable: (() => {
      const tableId = new TableId("", "position");
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    PlayerTable: (() => {
      const tableId = new TableId("", "player");
      return defineComponent(
        world,
        {
          health: RecsType.Number,
          ammo: RecsType.Number,
          rockets: RecsType.Number,
          lastDash: RecsType.Number,
          charge: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
