// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

enum Direction {
  NONE,
  LEFT,
  RIGHT,
  UP,
  DOWN
}

enum ActionType {
  NONE,
  MOVE,
  DASH,
  SHOOT,
  BLAST,
  PUNCH,
  CHARGE
}
