import { EntityID, getComponentValue } from "@latticexyz/recs";
import { useEffect } from "react";
import { useMUD } from "./MUDContext";

/* Autogenerated file. Do not edit manually. */

enum Direction {
  LEFT = 0,
  RIGHT = 1,
  UP = 2,
  DOWN = 3
}

export const useKeyboardMovement = () => {
  const {
    world,
    components: { PositionTable },
    network: { connectedAddress, signer },
    worldSend,
  } = useMUD();

  const moveTo = async (direction: Direction) => {
    // Create a World contract instance
    const s = signer.get();
    if (!s) throw new Error("No signer");

    const txResult = await worldSend("move", [direction]);
    await txResult.wait();
  };

  const moveBy = async (direction: Direction) => {
    const address = connectedAddress.get();
    if (!address) throw new Error("Not connected");
    const playerEntityId = address as EntityID;
    const playerEntity = world.registerEntity({ id: playerEntityId });

    const playerPosition = getComponentValue(PositionTable, playerEntity);

    if (playerPosition) {
      await moveTo(direction);
    } else {
      console.log(playerPosition)
        
      await moveTo(direction);
    }
  };

  useEffect(() => {
    const listener = (e: KeyboardEvent) => {
      if (e.key === "ArrowUp") {
        moveBy(Direction.DOW);
      }
      if (e.key === "ArrowDown") {
        moveBy(Direction.DOWN);
      }
      if (e.key === "ArrowLeft") {
        moveBy(Direction.LEFT);
      }
      if (e.key === "ArrowRight") {
        moveBy(Direction.RIGHT);
      }
    };

    window.addEventListener("keydown", listener);

    return () => window.removeEventListener("keydown", listener);
  }, [moveBy]);
};
