// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

uint256 constant _tableId = uint256(bytes32(abi.encodePacked(bytes16(""), bytes16("position"))));
uint256 constant PositionTableTableId = _tableId;

struct PositionTableData {
  uint16 x;
  uint16 y;
}

library PositionTable {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.UINT16;
    _schema[1] = SchemaType.UINT16;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](3);
    _schema[0] = SchemaType.ADDRESS;
    _schema[1] = SchemaType.UINT16;
    _schema[2] = SchemaType.UINT16;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](2);
    _fieldNames[0] = "x";
    _fieldNames[1] = "y";
    return ("PositionTable", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get x */
  function getX(address bot, uint16 game, uint16 round) internal view returns (uint16 x) {
    bytes32[] memory _primaryKeys = new bytes32[](3);
    _primaryKeys[0] = bytes32(bytes20((bot)));
    _primaryKeys[1] = bytes32(uint256((game)));
    _primaryKeys[2] = bytes32(uint256((round)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 0);
    return (uint16(Bytes.slice2(_blob, 0)));
  }

  /** Get x (using the specified store) */
  function getX(IStore _store, address bot, uint16 game, uint16 round) internal view returns (uint16 x) {
    bytes32[] memory _primaryKeys = new bytes32[](3);
    _primaryKeys[0] = bytes32(bytes20((bot)));
    _primaryKeys[1] = bytes32(uint256((game)));
    _primaryKeys[2] = bytes32(uint256((round)));

    bytes memory _blob = _store.getField(_tableId, _primaryKeys, 0);
    return (uint16(Bytes.slice2(_blob, 0)));
  }

  /** Set x */
  function setX(address bot, uint16 game, uint16 round, uint16 x) internal {
    bytes32[] memory _primaryKeys = new bytes32[](3);
    _primaryKeys[0] = bytes32(bytes20((bot)));
    _primaryKeys[1] = bytes32(uint256((game)));
    _primaryKeys[2] = bytes32(uint256((round)));

    StoreSwitch.setField(_tableId, _primaryKeys, 0, abi.encodePacked((x)));
  }

  /** Set x (using the specified store) */
  function setX(IStore _store, address bot, uint16 game, uint16 round, uint16 x) internal {
    bytes32[] memory _primaryKeys = new bytes32[](3);
    _primaryKeys[0] = bytes32(bytes20((bot)));
    _primaryKeys[1] = bytes32(uint256((game)));
    _primaryKeys[2] = bytes32(uint256((round)));

    _store.setField(_tableId, _primaryKeys, 0, abi.encodePacked((x)));
  }

  /** Get y */
  function getY(address bot, uint16 game, uint16 round) internal view returns (uint16 y) {
    bytes32[] memory _primaryKeys = new bytes32[](3);
    _primaryKeys[0] = bytes32(bytes20((bot)));
    _primaryKeys[1] = bytes32(uint256((game)));
    _primaryKeys[2] = bytes32(uint256((round)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 1);
    return (uint16(Bytes.slice2(_blob, 0)));
  }

  /** Get y (using the specified store) */
  function getY(IStore _store, address bot, uint16 game, uint16 round) internal view returns (uint16 y) {
    bytes32[] memory _primaryKeys = new bytes32[](3);
    _primaryKeys[0] = bytes32(bytes20((bot)));
    _primaryKeys[1] = bytes32(uint256((game)));
    _primaryKeys[2] = bytes32(uint256((round)));

    bytes memory _blob = _store.getField(_tableId, _primaryKeys, 1);
    return (uint16(Bytes.slice2(_blob, 0)));
  }

  /** Set y */
  function setY(address bot, uint16 game, uint16 round, uint16 y) internal {
    bytes32[] memory _primaryKeys = new bytes32[](3);
    _primaryKeys[0] = bytes32(bytes20((bot)));
    _primaryKeys[1] = bytes32(uint256((game)));
    _primaryKeys[2] = bytes32(uint256((round)));

    StoreSwitch.setField(_tableId, _primaryKeys, 1, abi.encodePacked((y)));
  }

  /** Set y (using the specified store) */
  function setY(IStore _store, address bot, uint16 game, uint16 round, uint16 y) internal {
    bytes32[] memory _primaryKeys = new bytes32[](3);
    _primaryKeys[0] = bytes32(bytes20((bot)));
    _primaryKeys[1] = bytes32(uint256((game)));
    _primaryKeys[2] = bytes32(uint256((round)));

    _store.setField(_tableId, _primaryKeys, 1, abi.encodePacked((y)));
  }

  /** Get the full data */
  function get(address bot, uint16 game, uint16 round) internal view returns (PositionTableData memory _table) {
    bytes32[] memory _primaryKeys = new bytes32[](3);
    _primaryKeys[0] = bytes32(bytes20((bot)));
    _primaryKeys[1] = bytes32(uint256((game)));
    _primaryKeys[2] = bytes32(uint256((round)));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _primaryKeys, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(
    IStore _store,
    address bot,
    uint16 game,
    uint16 round
  ) internal view returns (PositionTableData memory _table) {
    bytes32[] memory _primaryKeys = new bytes32[](3);
    _primaryKeys[0] = bytes32(bytes20((bot)));
    _primaryKeys[1] = bytes32(uint256((game)));
    _primaryKeys[2] = bytes32(uint256((round)));

    bytes memory _blob = _store.getRecord(_tableId, _primaryKeys, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(address bot, uint16 game, uint16 round, uint16 x, uint16 y) internal {
    bytes memory _data = encode(x, y);

    bytes32[] memory _primaryKeys = new bytes32[](3);
    _primaryKeys[0] = bytes32(bytes20((bot)));
    _primaryKeys[1] = bytes32(uint256((game)));
    _primaryKeys[2] = bytes32(uint256((round)));

    StoreSwitch.setRecord(_tableId, _primaryKeys, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(IStore _store, address bot, uint16 game, uint16 round, uint16 x, uint16 y) internal {
    bytes memory _data = encode(x, y);

    bytes32[] memory _primaryKeys = new bytes32[](3);
    _primaryKeys[0] = bytes32(bytes20((bot)));
    _primaryKeys[1] = bytes32(uint256((game)));
    _primaryKeys[2] = bytes32(uint256((round)));

    _store.setRecord(_tableId, _primaryKeys, _data);
  }

  /** Set the full data using the data struct */
  function set(address bot, uint16 game, uint16 round, PositionTableData memory _table) internal {
    set(bot, game, round, _table.x, _table.y);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, address bot, uint16 game, uint16 round, PositionTableData memory _table) internal {
    set(_store, bot, game, round, _table.x, _table.y);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (PositionTableData memory _table) {
    _table.x = (uint16(Bytes.slice2(_blob, 0)));

    _table.y = (uint16(Bytes.slice2(_blob, 2)));
  }

  /** Tightly pack full data using this table's schema */
  function encode(uint16 x, uint16 y) internal view returns (bytes memory) {
    return abi.encodePacked(x, y);
  }

  /* Delete all data for given keys */
  function deleteRecord(address bot, uint16 game, uint16 round) internal {
    bytes32[] memory _primaryKeys = new bytes32[](3);
    _primaryKeys[0] = bytes32(bytes20((bot)));
    _primaryKeys[1] = bytes32(uint256((game)));
    _primaryKeys[2] = bytes32(uint256((round)));

    StoreSwitch.deleteRecord(_tableId, _primaryKeys);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, address bot, uint16 game, uint16 round) internal {
    bytes32[] memory _primaryKeys = new bytes32[](3);
    _primaryKeys[0] = bytes32(bytes20((bot)));
    _primaryKeys[1] = bytes32(uint256((game)));
    _primaryKeys[2] = bytes32(uint256((round)));

    _store.deleteRecord(_tableId, _primaryKeys);
  }
}
